package cli

import (
	"testing"

	"github.com/spf13/cobra"
)

func TestNewDocsRoot(t *testing.T) {
	root := NewDocsRoot()
	if root == nil {
		t.Fatal("NewDocsRoot returned nil")
	}
	if got := root.Use; got != "mnemosyne" {
		t.Errorf("Use = %q, want %q", got, "mnemosyne")
	}
	if !root.DisableAutoGenTag {
		t.Error("root DisableAutoGenTag = false, want true")
	}

	if len(root.Commands()) == 0 {
		t.Fatal("expected subcommands to be registered, got none")
	}

	// Every descendant must inherit DisableAutoGenTag so cobra/doc does
	// not stamp a "Auto generated by spf13/cobra" footer that varies by
	// build host.
	walk(t, root)
}

func walk(t *testing.T, cmd *cobra.Command) {
	t.Helper()
	for _, child := range cmd.Commands() {
		if !child.DisableAutoGenTag {
			t.Errorf("subcommand %q DisableAutoGenTag = false, want true", child.Use)
		}
		walk(t, child)
	}
}
