.nh
.TH "MNEMOSYNE" "1" "May 2026" "Mnemosyne" "Mnemosyne Manual"

.SH NAME
mnemosyne-templates - List built-in chat templates available to transform


.SH SYNOPSIS
\fBmnemosyne templates [flags]\fP


.SH DESCRIPTION
List built-in chat templates available to transform


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for templates


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the settings file

.PP
\fB--verbose\fP[=false]
	enable debug logging


.SH SEE ALSO
\fBmnemosyne(1)\fP
