.nh
.TH "MNEMOSYNE" "1" "May 2026" "Mnemosyne" "Mnemosyne Manual"

.SH NAME
mnemosyne-survey - Inspect saved state and discover available groupings


.SH SYNOPSIS
\fBmnemosyne survey [flags]\fP


.SH DESCRIPTION
Inspect saved state and discover available groupings


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for survey


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the settings file

.PP
\fB--verbose\fP[=false]
	enable debug logging


.SH SEE ALSO
\fBmnemosyne(1)\fP
