.nh
.TH "MNEMOSYNE" "1" "May 2026" "Mnemosyne" "Mnemosyne Manual"

.SH NAME
mnemosyne-serializers - List available serializer formats


.SH SYNOPSIS
\fBmnemosyne serializers [flags]\fP


.SH DESCRIPTION
List available serializer formats


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for serializers


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the settings file

.PP
\fB--verbose\fP[=false]
	enable debug logging


.SH SEE ALSO
\fBmnemosyne(1)\fP
