.nh
.TH "MNEMOSYNE" "1" "May 2026" "Mnemosyne" "Mnemosyne Manual"

.SH NAME
mnemosyne - Export coding-assistant histories into anonymized archives


.SH SYNOPSIS
\fBmnemosyne [flags]\fP


.SH DESCRIPTION
Export coding-assistant histories into anonymized archives


.SH OPTIONS
\fB--config\fP=""
	path to the settings file

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for mnemosyne

.PP
\fB--verbose\fP[=false]
	enable debug logging


.SH SEE ALSO
\fBmnemosyne-attest(1)\fP, \fBmnemosyne-configure(1)\fP, \fBmnemosyne-extract(1)\fP, \fBmnemosyne-inspect(1)\fP, \fBmnemosyne-publish(1)\fP, \fBmnemosyne-runlog(1)\fP, \fBmnemosyne-serializers(1)\fP, \fBmnemosyne-survey(1)\fP, \fBmnemosyne-templates(1)\fP, \fBmnemosyne-transform(1)\fP, \fBmnemosyne-validate(1)\fP
