.nh
.TH "MNEMOSYNE" "1" "Jan 1970" "Mnemosyne" "Mnemosyne Manual"

.SH NAME
mnemosyne-runlog - Show saved workflow state


.SH SYNOPSIS
\fBmnemosyne runlog [flags]\fP


.SH DESCRIPTION
Show saved workflow state


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for runlog


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the settings file

.PP
\fB--verbose\fP[=false]
	enable debug logging


.SH SEE ALSO
\fBmnemosyne(1)\fP
