.nh
.TH "MNEMOSYNE" "1" "May 2026" "Mnemosyne" "Mnemosyne Manual"

.SH NAME
mnemosyne-validate - Validate a canonical JSONL export


.SH SYNOPSIS
\fBmnemosyne validate [flags]\fP


.SH DESCRIPTION
Validate a canonical JSONL export


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for validate

.PP
\fB--input\fP=""
	path to the JSONL file to validate


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the settings file

.PP
\fB--verbose\fP[=false]
	enable debug logging


.SH SEE ALSO
\fBmnemosyne(1)\fP
