.nh
.TH "MNEMOSYNE" "1" "Jan 1970" "Mnemosyne" "Mnemosyne Manual"

.SH NAME
mnemosyne-inspect - Enumerate detected groupings for a source scope


.SH SYNOPSIS
\fBmnemosyne inspect [flags]\fP


.SH DESCRIPTION
Enumerate detected groupings for a source scope


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for inspect

.PP
\fB--scope\fP=""
	source scope to inspect, or 'all'


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the settings file

.PP
\fB--verbose\fP[=false]
	enable debug logging


.SH SEE ALSO
\fBmnemosyne(1)\fP
